package com.huatuo.customer.domain;

import java.io.Serializable;

/**
 * 科室实体类
 * @author tangxiangqian0625
 *
 */
public class Specialty implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 7062777549776009417L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.grade
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.parent_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.mz_activated
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int mzActivated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.py_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String pyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.d_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String dCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.sort_no
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int sortNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_specialty.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.id
     *
     * @return the value of xt_specialty.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.id
     *
     * @param id the value for xt_specialty.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.code
     *
     * @return the value of xt_specialty.code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.code
     *
     * @param code the value for xt_specialty.code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.name
     *
     * @return the value of xt_specialty.name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.name
     *
     * @param name the value for xt_specialty.name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.grade
     *
     * @return the value of xt_specialty.grade
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.grade
     *
     * @param grade the value for xt_specialty.grade
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setGrade(int grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.parent_id
     *
     * @return the value of xt_specialty.parent_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.parent_id
     *
     * @param parentId the value for xt_specialty.parent_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.mz_activated
     *
     * @return the value of xt_specialty.mz_activated
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getMzActivated() {
        return mzActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.mz_activated
     *
     * @param mzActivated the value for xt_specialty.mz_activated
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setMzActivated(int mzActivated) {
        this.mzActivated = mzActivated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.py_code
     *
     * @return the value of xt_specialty.py_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getPyCode() {
        return pyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.py_code
     *
     * @param pyCode the value for xt_specialty.py_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setPyCode(String pyCode) {
        this.pyCode = pyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.d_code
     *
     * @return the value of xt_specialty.d_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getdCode() {
        return dCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.d_code
     *
     * @param dCode the value for xt_specialty.d_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setdCode(String dCode) {
        this.dCode = dCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.sort_no
     *
     * @return the value of xt_specialty.sort_no
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.sort_no
     *
     * @param sortNo the value for xt_specialty.sort_no
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setSortNo(int sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_specialty.del_flag
     *
     * @return the value of xt_specialty.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public boolean isDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_specialty.del_flag
     *
     * @param delFlag the value for xt_specialty.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDelFlag(boolean delFlag) {
        this.delFlag = delFlag;
    }

	
	

}
