package com.huatuo.customer.base.domain;

import java.io.Serializable;

public class XtEvidence implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1213L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_evidence.evidence_id
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    private String evidenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_evidence.institution
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    private String institution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_evidence.institution_img
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    private String institutionImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_evidence.type
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_evidence.create_time
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_evidence.name
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_evidence.moblie
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    private String moblie;
    private String vipCode;
    private String recommendCode;
    private String isPay;
    private String recommendedCode;
    private String qCellCore;
    public String getIsPay() {
		return isPay;
	}

	public void setIsPay(String isPay) {
		this.isPay = isPay;
	}

	public String getRecommendedCode() {
		return recommendedCode;
	}

	public void setRecommendedCode(String recommendedCode) {
		this.recommendedCode = recommendedCode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_evidence.evidence_id
     *
     * @return the value of xt_evidence.evidence_id
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public String getEvidenceId() {
        return evidenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_evidence.evidence_id
     *
     * @param evidenceId the value for xt_evidence.evidence_id
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public void setEvidenceId(String evidenceId) {
        this.evidenceId = evidenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_evidence.institution
     *
     * @return the value of xt_evidence.institution
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_evidence.institution
     *
     * @param institution the value for xt_evidence.institution
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_evidence.institution_img
     *
     * @return the value of xt_evidence.institution_img
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public String getInstitutionImg() {
        return institutionImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_evidence.institution_img
     *
     * @param institutionImg the value for xt_evidence.institution_img
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public void setInstitutionImg(String institutionImg) {
        this.institutionImg = institutionImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_evidence.type
     *
     * @return the value of xt_evidence.type
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_evidence.type
     *
     * @param type the value for xt_evidence.type
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }



    public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_evidence.name
     *
     * @return the value of xt_evidence.name
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_evidence.name
     *
     * @param name the value for xt_evidence.name
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_evidence.moblie
     *
     * @return the value of xt_evidence.moblie
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public String getMoblie() {
        return moblie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_evidence.moblie
     *
     * @param moblie the value for xt_evidence.moblie
     *
     * @mbggenerated Sat Nov 19 09:50:53 CST 2016
     */
    public void setMoblie(String moblie) {
        this.moblie = moblie;
    }

	public String getVipCode() {
		return vipCode;
	}

	public void setVipCode(String vipCode) {
		this.vipCode = vipCode;
	}

	public String getRecommendCode() {
		return recommendCode;
	}

	public void setRecommendCode(String recommendCode) {
		this.recommendCode = recommendCode;
	}

	public String getqCellCore() {
		return qCellCore;
	}

	public void setqCellCore(String qCellCore) {
		this.qCellCore = qCellCore;
	}
    
}